
export const metadata = {
    title: 'Create Next',
    description: 'Generated by create next app',
}

export default function Home() {
    return (
        <>
            <div className="md:container md:mx-auto">

            </div>
        </>
    )
}
