import {ListAuteurs} from "@/components/auteurs/ListAuteurs";

export const metadata = {
    title: 'Create Next',
    description: 'Generated by create next app',
}

async function getData() {

    const resAuteurs = await fetch(process.env.NEXT_PUBLIC_URL+'/api/auteurs');
    return await resAuteurs.json();

}

export default async function Home() {

    const data = await getData();
    return (
        <>
            <div className="md:container md:mx-auto">
                <ListAuteurs auteurs={data.auteurs}/>
            </div>
        </>
    )
}